# Configure Hugo:       https://gohugo.io/getting-started/configuration/#configuration-file
title:                  Hugo-RFi-Cover
baseURL:                "/"
# baseURL:              "https://cybmir.ru/"
# themes: hugo-rfi-bs5cover

languageCode:           ru
DefaultContentLanguage: ru
disableLanguages:       en
# languageCode:           en
# DefaultContentLanguage: en
# disableLanguages:       ru

enableInlineShortcodes: true

# bd5
markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           4

# Syntax Highlighting
pygmentsUseClasses:     true

enableRobotsTXT:        false
publishDir:             "@_site"

# применяются относительные ссылки. Тo turn relative URLs into absolute use
# canonifyURLs:         true.
canonifyURLs:           false


params:
# Brand
  logo:                 "/images/logo-cover.svg"
  title:                Cover
  description:          A one-page template for building simple and beautiful home pages.
# for meta
  summary: Very nice template
  authors:              "@mdo, wBuresh, Eric Fandor"
  site_version:         20210621rfi
  # option to specify the favicon image of the site
  # the path is relative to the folder "assetDir" of this configuration
  favicon:              "/images/favicon.svg"

# Оptions

  darkMode:             true
  # darkMode:           false

  # parameter used to specify if you want to minify the imported js
  jsMinify:             false
  # parameter used to specify if you want to minify the imported css
  cssMinify:            false
  # parameter used to specify if you want to calculate the css integrity
  cssIntegrity:         false
  # parameter used to specify if you want to calculate the js integrity
  jsIntegrity:          false
  # option to specify the main colour of the theme

  # mainColour:         "#F39200"
  # mainColour:         "#00d1b2"
  # bs $primary, $secondary, $success, $warning, $light
  mainColour:         "#0d6efd"
  # mainColour:         "#6c757d"
  # mainColour:         "#198754"
  # mainColour:         "#fd9c0d"
  # mainColour:         "#f8f9fa"

# homepage options
  homepage:
    # this options let you specify if you want a link to the homepage
    # it can be:        "none", "menu", "footer" or "menu+footer"
    # linkPosition:     "footer"
    # this options let you specify the text of the link to the homepage
    # linkText:         "Homepage"
    # option to specify the title in the homepage
    title:              Cover your page
    subtitle: Only one-page template for building simple and beautiful home pages.
    # option to specify the subtitle in the homepage
    summary: Download, edit the text, and add your own fullscreen background photo to make it your own.

## multi language support options
####################################
languages:
  en:
    languageName:       English
    weight:             2
    # title:            In English
  ru:
    languageName:       Russian
    # title:            На Русском
    weight:             1
      # Some sub-parameters of the "Homepage" and "footer" parameter

    params:
      homepage:
        title:          Золотая оправа вашего сайта
        subtitle:       одностраничный шаблон для создания простой и красивой главной страницы.
        summary: Загрузите, отредактируйте текст и добавьте свою собственную полноэкранную фоновую фотографию, чтобы сделать ее своей собственной.
